run:
  experiment_id: "run_1"
  world_size: 1
  distributed_training_strategy: "ddp"
  seed: 42

train:
  epochs: 30
  global_batch_size: 16
  lr: 0.0003
  seed: 42

model:
  name: "my-transformer"
  dtype: "float16"
  ref_model: ""
  ref_model_device: "cpu"

data:
  train_path: "data/train.jsonl"
  val_path: "data/val.jsonl"
  num_workers: 4

 
deepspeed:
  config: "./ds_config.json"
 
inference_engine:
  name: "vllm"
